# Generated by Django 4.2.7 on 2024-02-06 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("profiles", "0002_alter_staffprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Class ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Classroom Name"),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to="profiles.staffprofile",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classrooms",
                        to="profiles.studentprofile",
                    ),
                ),
                (
                    "teachers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="classrooms",
                        to="profiles.teacherprofile",
                    ),
                ),
            ],
        ),
    ]
