# Generated by Django 4.2.7 on 2024-03-31 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classrooms", "0001_initial"),
        ("profiles", "0002_alter_staffprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "description",
                    models.TextField(default="", verbose_name="Description"),
                ),
                ("content", models.TextField(default="[]", verbose_name="Content")),
                ("visits", models.IntegerField(default=0, verbose_name="Visits")),
                (
                    "submissions",
                    models.IntegerField(default=0, verbose_name="Submissions"),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="classrooms.classroom",
                        verbose_name="Classroom",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="profiles.teacherprofile",
                        verbose_name="Teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExamSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.exam",
                        verbose_name="Exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_submissions",
                        to="profiles.studentprofile",
                        verbose_name="Student",
                    ),
                ),
            ],
        ),
    ]
