# Generated by Django 4.2.7 on 2024-07-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="visits",
        ),
        migrations.AddField(
            model_name="exam",
            name="totalPoints",
            field=models.IntegerField(default=0, verbose_name="Total Points"),
        ),
    ]
