# Generated by Django 4.2.7 on 2024-07-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_remove_exam_visits_exam_totalpoints"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obtained_points",
                    models.TextField(default="[]", verbose_name="Obtained Points"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.examsubmission",
                        verbose_name="ExamSubmission",
                    ),
                ),
            ],
        ),
    ]
