# Generated by Django 4.2.7 on 2024-02-11 00:35

import classworks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classrooms", "0001_initial"),
        ("profiles", "0002_alter_staffprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classwork_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Classwork"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("due_date", models.DateTimeField(verbose_name="Due Date")),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classworks",
                        to="classrooms.classroom",
                        verbose_name="Classroom",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="classworks",
                        to="profiles.studentprofile",
                        verbose_name="Assigned Students",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classworks",
                        to="profiles.teacherprofile",
                        verbose_name="Assigned Teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassworkSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Submission"
                    ),
                ),
                (
                    "submission_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submission Time"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=classworks.models.classwork_submission_file_path,
                        verbose_name="File Upload",
                    ),
                ),
                (
                    "submission_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="Submission Text"
                    ),
                ),
                (
                    "classwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="classworks.classwork",
                        verbose_name="Classwork",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="profiles.studentprofile",
                        verbose_name="Student",
                    ),
                ),
            ],
        ),
    ]
