# Generated by Django 4.2.7 on 2024-03-26 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_staffprofile_date_of_birth_and_more"),
        ("classworks", "0003_classworkpubliccomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classworkpubliccomment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_comments",
                to="profiles.studentprofile",
                verbose_name="Student",
            ),
        ),
        migrations.AlterField(
            model_name="classworkpubliccomment",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="public_comments",
                to="profiles.teacherprofile",
                verbose_name="Assigned Teacher",
            ),
        ),
    ]
