# Generated by Django 4.2.7 on 2024-03-26 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_alter_staffprofile_date_of_birth_and_more"),
        ("classworks", "0004_alter_classworkpubliccomment_student_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassworkPrivateComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="User Type"
                    ),
                ),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "classwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_comments",
                        to="classworks.classwork",
                        verbose_name="Classwork",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_comments",
                        to="profiles.studentprofile",
                        verbose_name="Student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_comments",
                        to="profiles.teacherprofile",
                        verbose_name="Assigned Teacher",
                    ),
                ),
            ],
        ),
    ]
