# Generated by Django 4.2.7 on 2024-07-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classworks", "0006_remove_classworkprivatecomment_user_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classwork",
            name="total_points",
            field=models.IntegerField(default=0, verbose_name="Total Points"),
        ),
        migrations.AddField(
            model_name="classworksubmission",
            name="obtained_points",
            field=models.IntegerField(default=0, verbose_name="Obtained Points"),
        ),
    ]
