# Generated by Django 4.2.7 on 2024-02-02 01:10

from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_alter_admin_password_alter_staff_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_uid",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Teacher Profile ID"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Contact Info",
                    ),
                ),
                (
                    "permanent_address",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Permanent Address",
                    ),
                ),
                (
                    "present_address",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Present Address",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="Default.png",
                        null=True,
                        upload_to=profiles.models.staff_profile_picture_path,
                    ),
                ),
                (
                    "teacher",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="users.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_uid",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Student Profile ID"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "father_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Father's Name",
                    ),
                ),
                (
                    "father_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Father's Contact Info",
                    ),
                ),
                (
                    "mother_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Mother's Name",
                    ),
                ),
                (
                    "mother_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Mother's Contact Info",
                    ),
                ),
                (
                    "permanent_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Permanent Address",
                    ),
                ),
                (
                    "present_address",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Present Address",
                    ),
                ),
                (
                    "date_of_birth",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Date of Birth",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="Default.png",
                        null=True,
                        upload_to=profiles.models.student_profile_picture_path,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.student",
                        verbose_name="Student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_uid",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Staff Profile ID"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "contact_info",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Contact Info",
                    ),
                ),
                (
                    "permanent_address",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Permanent Address",
                    ),
                ),
                (
                    "present_address",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Present Address",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        default="Default.png",
                        null=True,
                        upload_to=profiles.models.staff_profile_picture_path,
                    ),
                ),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="users.staff",
                    ),
                ),
            ],
        ),
    ]
