# Generated by Django 4.2.7 on 2024-02-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="date_of_birth",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Date of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="date_of_birth",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Date of Birth"
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="date_of_birth",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Date of Birth"
            ),
        ),
    ]
