# Generated by Django 4.2.7 on 2024-02-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Admin ID"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Username"
                    ),
                ),
                ("password", models.CharField(max_length=20, verbose_name="Password")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Staff ID"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="Username")),
                ("password", models.CharField(max_length=20, verbose_name="Password")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Student ID"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="Username")),
                ("password", models.CharField(max_length=20, verbose_name="Password")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Teacher ID"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="Username")),
                ("password", models.CharField(max_length=20, verbose_name="Password")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
